# Generated by Django 5.1.5 on 2025-02-03 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0004_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_photo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
