# Generated by Django 5.1.5 on 2025-02-05 10:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0007_defaultapplication_remove_document_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultapplication',
            name='deadline_days',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='userapplication',
            name='deadline_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
