# Generated by Django 5.1.5 on 2025-02-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0010_question_remove_user_interests_remove_user_user_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_multiple_answer',
            field=models.BooleanField(default=False),
        ),
    ]
