# Generated by Django 5.1.5 on 2025-02-11 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0011_question_is_multiple_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='is_multiple_answer',
            field=models.BooleanField(default=False, verbose_name='Можно выбрать несколько ответов'),
        ),
    ]
