# Generated by Django 5.1.5 on 2025-02-13 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0012_alter_question_is_multiple_answer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Ответ на вопрос для регистрации', 'verbose_name_plural': 'Ответы на вопросы для регистрации'},
        ),
        migrations.AlterModelOptions(
            name='applicationdocument',
            options={'verbose_name': 'Документ для заполнения заявки', 'verbose_name_plural': 'Документы для заполнения заявок'},
        ),
        migrations.AlterModelOptions(
            name='defaultapplication',
            options={'verbose_name': 'Дефолтная заявка для всех пользователей', 'verbose_name_plural': 'Дефолтные заявки для всех пользователей'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопрос для регистрации', 'verbose_name_plural': 'Вопросы для регистрации'},
        ),
        migrations.AlterModelOptions(
            name='useranswer',
            options={'verbose_name': 'Ответ пользователя при регистрации', 'verbose_name_plural': 'Ответы пользователей при регистрации'},
        ),
        migrations.AlterModelOptions(
            name='userapplication',
            options={'verbose_name': 'Статус Заявки пользователя', 'verbose_name_plural': 'Статусы заявок пользователей'},
        ),
        migrations.AlterModelOptions(
            name='userdocument',
            options={'verbose_name': 'Документ пользователя', 'verbose_name_plural': 'Документы пользователей'},
        ),
    ]
