# Generated by Django 5.1.5 on 2025-04-08 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0016_question_text_en_question_text_ru_question_text_uz'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='text_en',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='text_ru',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='text_uz',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
