# Generated by Django 5.1.5 on 2025-04-08 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0017_answer_text_en_answer_text_ru_answer_text_uz'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultapplication',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='defaultapplication',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='defaultapplication',
            name='description_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='defaultapplication',
            name='required_documents_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='defaultapplication',
            name='required_documents_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='defaultapplication',
            name='required_documents_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='defaultapplication',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='defaultapplication',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='defaultapplication',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
