# Generated by Django 5.1.5 on 2025-04-08 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0018_defaultapplication_description_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defaultapplication',
            name='description',
        ),
        migrations.RemoveField(
            model_name='defaultapplication',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='defaultapplication',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='defaultapplication',
            name='description_uz',
        ),
        migrations.RemoveField(
            model_name='defaultapplication',
            name='required_documents',
        ),
        migrations.RemoveField(
            model_name='defaultapplication',
            name='required_documents_en',
        ),
        migrations.RemoveField(
            model_name='defaultapplication',
            name='required_documents_ru',
        ),
        migrations.RemoveField(
            model_name='defaultapplication',
            name='required_documents_uz',
        ),
    ]
