# Generated by Django 5.1.5 on 2025-01-31 11:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_img', models.ImageField(upload_to='country/')),
                ('name_ru', models.CharField(max_length=256)),
                ('name_en', models.CharField(blank=True, max_length=256, null=True)),
                ('about_universities', models.TextField()),
                ('advantages_universities', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Directions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(max_length=256, verbose_name='Направления')),
            ],
        ),
        migrations.CreateModel(
            name='Universities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_img', models.ImageField(upload_to='university/')),
                ('university_name', models.CharField(max_length=256, verbose_name='Название университета')),
                ('is_state', models.BooleanField(default=True, verbose_name='Государственный университет')),
                ('city', models.CharField(max_length=256, verbose_name='Город')),
                ('year_of_study', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Год обучения')),
                ('year_founded', models.IntegerField(validators=[django.core.validators.MaxValueValidator(2025)], verbose_name='Год основания')),
                ('students_count', models.IntegerField(verbose_name='Количество студентов')),
                ('international_students_count', models.IntegerField(verbose_name='Количество иностранных студентов')),
                ('number_of_grants', models.IntegerField(verbose_name='Количество грантов в проценте')),
                ('rating_qs', models.IntegerField()),
                ('rating_the', models.IntegerField()),
                ('history_university', models.TextField(verbose_name='История университета')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='universities', to='universities_app.country', verbose_name='Страна')),
                ('university_directions', models.ManyToManyField(related_name='universities', to='universities_app.directions', verbose_name='Напраления университета')),
            ],
        ),
    ]
