# Generated by Django 5.1.5 on 2025-04-08 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='name_ru',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='name_en',
            new_name='short_name',
        ),
        migrations.AddField(
            model_name='universities',
            name='city_en',
            field=models.CharField(max_length=256, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='universities',
            name='city_ru',
            field=models.CharField(max_length=256, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='universities',
            name='city_uz',
            field=models.CharField(max_length=256, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='universities',
            name='history_university_en',
            field=models.TextField(null=True, verbose_name='История университета'),
        ),
        migrations.AddField(
            model_name='universities',
            name='history_university_ru',
            field=models.TextField(null=True, verbose_name='История университета'),
        ),
        migrations.AddField(
            model_name='universities',
            name='history_university_uz',
            field=models.TextField(null=True, verbose_name='История университета'),
        ),
    ]
