# Generated by Django 5.1.5 on 2025-04-08 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities_app', '0002_rename_name_ru_country_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='about_universities_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='about_universities_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='about_universities_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='advantages_universities_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='advantages_universities_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='advantages_universities_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='name_en',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='name_ru',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='name_uz',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
