# Generated by Django 5.1.5 on 2025-06-23 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities_app', '0003_country_about_universities_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='directions',
            name='direction_en',
            field=models.CharField(max_length=256, null=True, verbose_name='Направления'),
        ),
        migrations.AddField(
            model_name='directions',
            name='direction_ru',
            field=models.CharField(max_length=256, null=True, verbose_name='Направления'),
        ),
        migrations.AddField(
            model_name='directions',
            name='direction_uz',
            field=models.CharField(max_length=256, null=True, verbose_name='Направления'),
        ),
    ]
