# Generated by Django 5.1.5 on 2025-06-23 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities_app', '0004_directions_direction_en_directions_direction_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='universities',
            name='number_of_grants',
        ),
        migrations.AddField(
            model_name='universities',
            name='acceptance_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
