# Generated by Django 5.1.5 on 2025-06-23 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities_app', '0005_remove_universities_number_of_grants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='universities',
            name='rating_us_news',
            field=models.IntegerField(default=999),
        ),
        migrations.AlterField(
            model_name='universities',
            name='acceptance_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Процент зачисления'),
        ),
    ]
