# Generated by Django 5.1.5 on 2025-06-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities_app', '0006_universities_rating_us_news_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='manual_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Позиция в списке'),
        ),
    ]
