# Generated by Django 5.1.5 on 2025-09-16 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities_app', '0007_country_manual_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='average_expenses',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='edu_quality_rank',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='gdp',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='universities_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='universities_top300_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
