# Generated by Django 5.1.5 on 2025-09-16 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities_app', '0008_country_average_expenses_country_edu_quality_rank_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='universities',
            name='website_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='universities',
            name='school_categories',
            field=models.ManyToManyField(blank=True, to='universities_app.schoolcategory'),
        ),
    ]
