# Generated by Django 5.1.5 on 2025-09-16 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities_app', '0009_schoolcategory_universities_website_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolcategory',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='schoolcategory',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='schoolcategory',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
