# Generated by Django 5.1.5 on 2025-01-31 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertDirections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(max_length=512, verbose_name='Направления')),
            ],
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='expert/')),
                ('name', models.CharField(max_length=256)),
                ('phone_number', models.CharField(max_length=20)),
                ('job', models.CharField(max_length=256, verbose_name='Кем работает')),
                ('success', models.IntegerField(verbose_name='Успешных зачислений')),
                ('experience', models.IntegerField(verbose_name='Опыт работы')),
                ('language', models.CharField(max_length=512, verbose_name='Языки')),
                ('education', models.CharField(max_length=512, verbose_name='Образования')),
                ('expert_directions', models.ManyToManyField(related_name='experts', to='experts_app.expertdirections', verbose_name='Направления эксперта')),
            ],
        ),
    ]
