# Generated by Django 5.1.5 on 2025-02-01 10:08

import mdeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experts_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expert',
            name='expert_directions',
        ),
        migrations.RemoveField(
            model_name='expert',
            name='education',
        ),
        migrations.RemoveField(
            model_name='expert',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='expert',
            name='language',
        ),
        migrations.RemoveField(
            model_name='expert',
            name='success',
        ),
        migrations.AddField(
            model_name='expert',
            name='expert_about',
            field=mdeditor.fields.MDTextField(default=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ExpertDirections',
        ),
    ]
