# Generated by Django 5.1.5 on 2025-02-07 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts_app', '0002_remove_expert_expert_directions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expert',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='expert',
            name='telegram_url',
            field=models.URLField(default='https://t.me/'),
        ),
    ]
