# Generated by Django 5.1.5 on 2025-02-07 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts_app', '0003_remove_expert_phone_number_expert_telegram_url'),
        ('universities_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessStories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='stories_success/')),
                ('name', models.CharField(max_length=256)),
                ('about', models.TextField()),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='successes', to='universities_app.universities')),
            ],
        ),
    ]
