# Generated by Django 5.1.5 on 2025-02-07 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts_app', '0004_successstories'),
    ]

    operations = [
        migrations.AddField(
            model_name='successstories',
            name='short_about',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
    ]
