# Generated by Django 5.1.5 on 2025-02-12 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts_app', '0006_remove_successstories_university_and_more'),
        ('universities_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='successstories',
            name='university',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='successes', to='universities_app.universities'),
            preserve_default=False,
        ),
    ]
