# Generated by Django 5.1.5 on 2025-04-08 05:24

import mdeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts_app', '0007_successstories_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='expert_about_en',
            field=mdeditor.fields.MDTextField(null=True),
        ),
        migrations.AddField(
            model_name='expert',
            name='expert_about_ru',
            field=mdeditor.fields.MDTextField(null=True),
        ),
        migrations.AddField(
            model_name='expert',
            name='expert_about_uz',
            field=mdeditor.fields.MDTextField(null=True),
        ),
        migrations.AddField(
            model_name='expert',
            name='job_en',
            field=models.CharField(max_length=256, null=True, verbose_name='Кем работает'),
        ),
        migrations.AddField(
            model_name='expert',
            name='job_ru',
            field=models.CharField(max_length=256, null=True, verbose_name='Кем работает'),
        ),
        migrations.AddField(
            model_name='expert',
            name='job_uz',
            field=models.CharField(max_length=256, null=True, verbose_name='Кем работает'),
        ),
        migrations.AddField(
            model_name='successstories',
            name='about_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='successstories',
            name='about_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='successstories',
            name='about_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='successstories',
            name='short_about_en',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='successstories',
            name='short_about_ru',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='successstories',
            name='short_about_uz',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
