# Generated by Django 5.1.5 on 2025-06-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts_app', '0008_expert_expert_about_en_expert_expert_about_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='name_en',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='expert',
            name='name_ru',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='expert',
            name='name_uz',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
