# Generated by Django 5.1.5 on 2025-06-23 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts_app', '0009_expert_name_en_expert_name_ru_expert_name_uz'),
    ]

    operations = [
        migrations.AddField(
            model_name='successstories',
            name='name_en',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='successstories',
            name='name_ru',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='successstories',
            name='name_uz',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
