# Generated by Django 5.1.5 on 2025-02-07 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts_app', '0005_successstories_short_about'),
        ('services_app', '0002_alter_service_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='experts',
            field=models.ManyToManyField(related_name='services', to='experts_app.expert'),
        ),
        migrations.CreateModel(
            name='ServiceApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('approved', 'Одобрено')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='services_app.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
