# Generated by Django 5.1.5 on 2025-02-08 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0003_service_experts_serviceapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationrequest',
            name='question',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
