# Generated by Django 5.1.5 on 2025-02-12 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0004_consultationrequest_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationrequest',
            name='status',
            field=models.CharField(choices=[('not_answered', 'Не отвечено'), ('in_progress', 'Отвечают'), ('answered', 'Отвечено')], default='not_answered', max_length=20),
        ),
    ]
