# Generated by Django 5.1.5 on 2025-02-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0005_consultationrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationrequest',
            name='answered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
