# Generated by Django 5.1.5 on 2025-02-12 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0006_consultationrequest_answered_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидание'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=20),
        ),
    ]
