# Generated by Django 5.1.5 on 2025-02-18 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0007_alter_serviceapplication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationrequest',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
