# Generated by Django 5.1.5 on 2025-09-16 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0009_service_description_en_service_description_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name='DayOfWeeks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name='EducationLevels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=155)),
            ],
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='service_of_interest',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='services_app.consultationservices'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='day_week',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='services_app.dayofweeks'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='level_education',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='services_app.educationlevels'),
            preserve_default=False,
        ),
    ]
