# Generated by Django 5.1.5 on 2025-09-17 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0010_consultationservices_dayofweeks_educationlevels_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationservices',
            name='service_en',
            field=models.CharField(max_length=155, null=True),
        ),
        migrations.AddField(
            model_name='consultationservices',
            name='service_ru',
            field=models.CharField(max_length=155, null=True),
        ),
        migrations.AddField(
            model_name='consultationservices',
            name='service_uz',
            field=models.CharField(max_length=155, null=True),
        ),
        migrations.AddField(
            model_name='dayofweeks',
            name='week_en',
            field=models.CharField(max_length=155, null=True),
        ),
        migrations.AddField(
            model_name='dayofweeks',
            name='week_ru',
            field=models.CharField(max_length=155, null=True),
        ),
        migrations.AddField(
            model_name='dayofweeks',
            name='week_uz',
            field=models.CharField(max_length=155, null=True),
        ),
        migrations.AddField(
            model_name='educationlevels',
            name='level_en',
            field=models.CharField(max_length=155, null=True),
        ),
        migrations.AddField(
            model_name='educationlevels',
            name='level_ru',
            field=models.CharField(max_length=155, null=True),
        ),
        migrations.AddField(
            model_name='educationlevels',
            name='level_uz',
            field=models.CharField(max_length=155, null=True),
        ),
    ]
