# Generated by Django 5.1.5 on 2025-01-31 11:43

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_img', models.ImageField(upload_to='news/')),
                ('news_title', models.CharField(max_length=256)),
                ('news_about', models.CharField(max_length=512, verbose_name='Кратко о новости')),
                ('date_added', models.DateField(default=datetime.date.today, verbose_name='Дата добавления')),
                ('news_description', models.TextField(verbose_name='Полное описание')),
                ('show_news', models.BooleanField(default=True, verbose_name='Показывать новость')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='news', to='news_app.category')),
            ],
        ),
    ]
