# Generated by Django 5.1.5 on 2025-04-08 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0003_notification_usernotification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_en',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='category_ru',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='category_uz',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='news_about_en',
            field=models.CharField(max_length=512, null=True, verbose_name='Кратко о новости'),
        ),
        migrations.AddField(
            model_name='news',
            name='news_about_ru',
            field=models.CharField(max_length=512, null=True, verbose_name='Кратко о новости'),
        ),
        migrations.AddField(
            model_name='news',
            name='news_about_uz',
            field=models.CharField(max_length=512, null=True, verbose_name='Кратко о новости'),
        ),
        migrations.AddField(
            model_name='news',
            name='news_description_en',
            field=models.TextField(null=True, verbose_name='Полное описание'),
        ),
        migrations.AddField(
            model_name='news',
            name='news_description_ru',
            field=models.TextField(null=True, verbose_name='Полное описание'),
        ),
        migrations.AddField(
            model_name='news',
            name='news_description_uz',
            field=models.TextField(null=True, verbose_name='Полное описание'),
        ),
        migrations.AddField(
            model_name='news',
            name='news_title_en',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='news_title_ru',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='news_title_uz',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
