# Generated by Django 5.1.5 on 2025-03-28 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('additionals_app', '0003_privacypolicy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrivacyPolicy',
        ),
    ]
