# Generated by Django 5.1.5 on 2025-04-08 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additionals_app', '0004_delete_privacypolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqmodel',
            name='answer_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faqmodel',
            name='answer_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faqmodel',
            name='answer_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faqmodel',
            name='question_en',
            field=models.CharField(max_length=156, null=True),
        ),
        migrations.AddField(
            model_name='faqmodel',
            name='question_ru',
            field=models.CharField(max_length=156, null=True),
        ),
        migrations.AddField(
            model_name='faqmodel',
            name='question_uz',
            field=models.CharField(max_length=156, null=True),
        ),
    ]
