# Generated by Django 5.1.5 on 2025-02-12 08:54

import mdeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestStart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', mdeditor.fields.MDTextField()),
            ],
        ),
        migrations.AddField(
            model_name='test',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
