# Generated by Django 5.1.5 on 2025-04-08 05:44

import mdeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0003_teststart_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='testanswer',
            name='answer_en',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='testanswer',
            name='answer_ru',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='testanswer',
            name='answer_uz',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='question_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='question_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='question_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='teststart',
            name='description_en',
            field=mdeditor.fields.MDTextField(null=True),
        ),
        migrations.AddField(
            model_name='teststart',
            name='description_ru',
            field=mdeditor.fields.MDTextField(null=True),
        ),
        migrations.AddField(
            model_name='teststart',
            name='description_uz',
            field=mdeditor.fields.MDTextField(null=True),
        ),
        migrations.AddField(
            model_name='teststart',
            name='title_en',
            field=models.CharField(max_length=152, null=True),
        ),
        migrations.AddField(
            model_name='teststart',
            name='title_ru',
            field=models.CharField(max_length=152, null=True),
        ),
        migrations.AddField(
            model_name='teststart',
            name='title_uz',
            field=models.CharField(max_length=152, null=True),
        ),
    ]
